[package]
name = "snake-game"
version = "0.1.0"
edition = "2021"

[dependencies]
console_engine = "2.6.0"
device_query = "1.1.3"
rand = "0.8.5"
tty-read = { git = "https://github.com/timvisee/tty-read-rs" }
